### ISSUE TITLE
Developer note - Delimiter Tag

### ISSUE THREAD

**Issue by fvet** [rvanbekkum/vsc-xliff-sync#100]
Hi @rvanbekkum 

I'm trying to prepare the move away to **AL Language Tools** to **XLIFF Sync** here internally.
I think we can easily adopt our way of working and achieve the same (and much better results) with **XLIFF Sync**.

However, some developers currently use a - nice - work-around to auto-translate the comments (upfront inside the AL files, not after the XLIFF files have been synced). In order not to offend anyone, I'd still like to - temporarily ? - support this way of working.

E.g. following could the format used when adding new labels, captions, ...
(Mind the " " surrounding the values to be translated)

`Caption = 'Item No.', Comment = 'fr-BE="Item No.",nl-BE="Item No."';`

- With some shortcuts magic (Ctrl+D / Ctrl+F2), the developer select e.g. all fr-BE tags.
- Then, moves twice to the right and by using the **Bracket Selection** extension (Alt+A) can easily select everything within the " ".
- If we would remove the " " (as Xliff snippets suggest), we won't be able to select the full text accompanying fr-BE.
- Once the selecting is made, using the VS Code Google Translate, we can batch translate all at once.

Result would be

`Caption = 'Item No.', Comment = 'fr-BE="N° article",nl-BE="Artikelnr."';`

Animation below shows the current way of working (not yet using the proper language tags )

![google](https://user-images.githubusercontent.com/25268332/154312710-88c4a02c-1e3a-4d6e-a36f-7d5dcb53ebc7.gif)

However, when XLIFF Sync parses the developer notes (using ','  as separator), we still have " " inside the translation / target value.

![image](https://user-images.githubusercontent.com/25268332/154313301-ef7ba78d-9054-4169-b51b-62a649e6a1c1.png)

Would it be an option to provide a new '**Parse From Developer Note Delimiter**' setting (cfr. separator), so we can exclude the " " from the translated result?

![image](https://user-images.githubusercontent.com/25268332/154310747-7f7a6c37-9d8e-48d0-b45c-ea6b5cfe1633.png)

**Comment by rvanbekkum** [comment]
Hi @fvet,
So if I understand correctly, you would like an option to have some characters trimmed from the translation?
For example, have:
```json
{
    "parseFromDeveloperNoteTrimCharacters": "\""
}
```
Would that suit your needs?

**Comment by fvet** [comment]
Yes, that would do it. Trim the mentioned **leading / trailing** character (") from the translation.

**Comment by fvet** [comment]
Hi @rvanbekkum. Any timing on when this would make the next release?

**Comment by rvanbekkum** [comment]
Hi @fvet,
I think it might be at the end of March the earliest. The past and upcoming days I did not have much time to spent on changes. I also still want to include the changes last suggested in https://github.com/rvanbekkum/vsc-xliff-sync/issues/87 in an upcoming release (even though it has been some time) as I do think they might be useful!

**Comment by rvanbekkum** [comment]
A change for this is ready for the next release and has been checked in on the `develop` branch, commit https://github.com/rvanbekkum/vsc-xliff-sync/commit/fc0ba6a4fba177da831bf81101d76e33982286a8.

**Comment by fvet** [comment]
Hi Rob, thanks for the update.

Any timing on when this new feature will be (pre-)released? 
Looking forward to test ;)

**Comment by rvanbekkum** [comment]
Released in version [1.3.0](https://github.com/rvanbekkum/vsc-xliff-sync/releases/tag/1.3.0).

**Comment by dannoe** [comment]
@fvet Just out of curiosity: Was replacing the old format (with ") with the new format (without ") not an option? Could be done with a single regular expression and Find&Replace

**Comment by fvet** [comment]
> * Then, moves twice to the right and by using the **Bracket Selection** extension (Alt+A) can easily select everything within the " ".

As referered to in my initial post, some of the developers use the [Bracket Selection](https://marketplace.visualstudio.com/items?itemName=chunsen.bracket-select) extension (Alt+A) to easily select everything within the " " to translate e.g. with [VS Code Google Translate](https://marketplace.visualstudio.com/items?itemName=funkyremi.vscode-google-translate).

If we would remove the " ", we won't be able to select the full text accompanying nl-BE.
