### ISSUE TITLE
[Bug] Sync with detectSourceTextChanges and parseFromDeveloperNoteOverwrite does not work for en-US

### ISSUE THREAD

**Issue by FlorianNoeverGOB** [rvanbekkum/vsc-xliff-sync#123]
We use 2 defined languages: en-US and de-DE. So in total we have 3 files:
Test-Project.g.xlf
Test-Project.en-US.xlf
Test-Project.de-DE.xlf

When changing a Translation and its Source Text, then building and then Syncing the additional language (here de-DE) get its Translation correctly. But en-US is set to `needs-adaptation` and has its old source text although `detectSourceTextChanges` is set to `false` and `parseFromDeveloperNoteOverwrite` is set to true.

These are the Settings we use:
```json
"xliffSync.copyFromSourceForSameLanguage": true,
"xliffSync.detectSourceTextChanges": false,
"xliffSync.baseFile": "Test-Project.g.xlf",
"xliffSync.needWorkTranslationRules": [
    "OptionMemberCount",
    "OptionLeadingSpaces",
    "Placeholders",
    "SourceEqualsTarget",
    "ConsecutiveSpacesConsistent"
],
"xliffSync.autoCheckNeedWorkTranslations": true,
"xliffSync.parseFromDeveloperNote": true,
"xliffSync.parseFromDeveloperNoteOverwrite": true,
"xliffSync.autoCheckMissingTranslations": true,
"xliffSync.keepEditorOpenAfterSync": false,
```

[Test-Project.zip](https://github.com/user-attachments/files/16588202/Test-Project.zip) (Only AL Objects, Translations and Settings)

**Comment by rvanbekkum** [comment]
Hi @FlorianNoeverGOB,
The current behaviour is correct. I notice you have `"xliffSync.copyFromSourceForSameLanguage": true` in your settings, and so I suspect setting `"xliffSync.copyFromSourceOverwrite": true` should get you the behaviour that you want, i.e., overwriting the translation/target text whenever the source text changes.

Please let me know if this helps you resolve your issue, or if you have any other questions.
For now I will close the issue, but if there is anything I missed, then please let me know. 😉

**Comment by FlorianNoeverGOB** [comment]
This fixed the issue. Thanks :)
