### ISSUE TITLE
The number of placeholders does not match expected

### ISSUE THREAD

**Issue by fvet** [rvanbekkum/vsc-xliff-sync#14]
In the sample code below, I would have expected an 'The number of placeholders does not match' warning since the target value (%2) does no longer match the number of placeholders in the source text.

```
<trans-unit id="Codeunit 2443601710 - NamedType 1680901191" size-unit="char" translate="yes" xml:space="preserve">
          <source>%1 does not contain costs.</source>
          <target>%1 bevat geen kosten (%2).</target>
          <note from="Developer" annotates="general" priority="2"/>
          <note from="Xliff Generator" annotates="general" priority="3">Codeunit NVT Purchase Tariff Period Mgt - NamedType NoCostsAvailableErr</note>
        </trans-unit>
```

**Comment by rvanbekkum** [comment]
Function `checkForPlaceHolderMismatch` should have also checked the other way around. 
Right now it first checks what the placeholders in the source text are, and then it verifies if these are also present in the translation text.
It should also do this the other way around.
Also, I think it should account for multiple occurrences of the same placeholder, which it does not yet.

Thank you for reporting!
