### ISSUE TITLE
[Feature Request] Enable 'Need Work Translation' for 'PromotedActionCategories' property

### ISSUE THREAD

**Issue by fvet** [rvanbekkum/vsc-xliff-sync#15]
Untill MS has found a decent way to manage / extend the ribbon / action groups, we still have to struglle with the 'PromotedActionCategories'. This is also a property prone to errors, due to the list of options. Would be good if the translation for 'PromotedActionCategories' property is tested the same way as the translation for the 'OptionCaption' property, showing 'number of option mismatch errors' in below case.

```
<trans-unit id="Page 1185325318 - Property 2019332006" size-unit="char" translate="yes" xml:space="preserve">
          <source>New,Process,Report,Purchase Document</source>
          <target state="translated">Nieuw,Verwerken,Lijst</target>
          <note from="Developer" annotates="general" priority="2"/>
          <note from="Xliff Generator" annotates="general" priority="3">Page NVT Purchase Tariffs - Property PromotedActionCategories</note>
        </trans-unit>
```

**Comment by rvanbekkum** [comment]
Available in release [0.2.0](https://github.com/rvanbekkum/vsc-xliff-sync/releases/tag/0.2.0).

**Comment by fvet** [comment]
Thanks!

PS: You should get your extension listed at https://marketplace.visualstudio.com/items?itemName=waldo.al-extension-pack to get more traction ;)

**Comment by rvanbekkum** [comment]
Great news: The extension is now finally available in the VS marketplace!
https://marketplace.visualstudio.com/items?itemName=rvanbekkum.xliff-sync

I will see if I can get the extension listed in that extension pack as well.
