### ISSUE TITLE
Feature Request: multiple base files in a workspace

### ISSUE THREAD

**Issue by RafaelKoch** [rvanbekkum/vsc-xliff-sync#23]
Hi!

We tested this very interesting VS Code Extension and found it could be a lot of help. 

We are working with a multi-root workspace that contains many AL Extensions. Yet xliff-sync places only one base file into the workspace settings file. That does not make too much sense since we would need to constantly change the config as we work through the individual extensions.

So the request would be: Allow to configure a base file per workspace folder.

**Comment by rvanbekkum** [comment]
Support for multi-root workspaces has been shipped in version 0.3.0.
Please try it out and let me know what you think and/or if you run into any issues.

**Comment by RafaelKoch** [comment]
My hero! Will try it this week.
