### ISSUE TITLE
[Feature] Check on consecutive spaces

### ISSUE THREAD

**Issue by fvet** [rvanbekkum/vsc-xliff-sync#25]
To improve the translation quality, it would be interesting if we could have 2 new rules:

- Check for consecutive spaces (no matter source/target)
- Check if consecutive spaces occur in source but not in target (or vice versa)

This would eliminate some minor issues as shown below:

![image](https://user-images.githubusercontent.com/25268332/66743628-a731f280-ee7a-11e9-8d65-13c090537544.png)

**Comment by rvanbekkum** [comment]
Good idea.
Maybe I could also add a check that sentences that end with a period (".") in the source, should also end with a period in the translation, while I am at it.
I noticed translators forget that one as well occasionally.

**Comment by fvet** [comment]
FYI, I don't use the 'period' check a lot, since we often have mixes on 'No.' versus 'Nummer' or 'Sales No.' vs 'Nr. Verkoop', ...

![image](https://user-images.githubusercontent.com/25268332/66749225-96d54400-ee89-11e9-9c76-d5a0f0bd45e6.png)

**Comment by rvanbekkum** [comment]
Can I ask which software you are using (as seen in your screenshots)? Seems useful to scan and check for such punctuation errors.

**Comment by fvet** [comment]
I've downloaded a trial of Aceproof to test the quality of the translations. The rather 'technical' thinks (punctuations, double spaces, ...) seem valid to add to XLIFF (compared to the current 'Needs technical work' checks). 

Other recommendations about 'consistency' should be part of a QA tool.

https://www.aceproof.com/

**Comment by rvanbekkum** [comment]
The suggested checks are shipped in version 0.3.1.
