### ISSUE TITLE
Show more details on"needs-adaptation"

### ISSUE THREAD

**Issue by pri-kise** [rvanbekkum/vsc-xliff-sync#33]
I have to translations where I got the `state="needs-adaptation"`, but I don't know what has to be changed?

I have the following settings enbled:
```
 "xliffSync.needWorkTranslationRules": [
        "OptionMemberCount",
        "OptionLeadingSpaces",
        "Placeholders",
        "ConsecutiveSpacesConsistent",
        "ConsecutiveSpacesExist"
    ]
```

Or is there any  way to show more output in the console?

**Comment by rvanbekkum** [comment]
Dear @pri-kise,
Thank you for reporting your issue.

The "XLIFF: Check for Need Work Translations" command will add an "XLIFF Sync" note to the trans-unit which describes the detected problem.
For example:
```xml
<trans-unit id="Table 1844763286 - Field 1352224975 - Property 62802879" size-unit="char" translate="yes" xml:space="preserve">
    <source>Print,Preview,Print/Preview,All</source>
    <target state="needs-adaptation">Drucken, Vorschau,Drucken/Vorschau,Alles</target>
    <note from="XLIFF Sync" annotates="general" priority="1">Problem detected: The leading spaces in the option values of the source and translation text do not match.</note>
    <note from="Developer" annotates="general" priority="2"/>
    <note from="Xliff Generator" annotates="general" priority="3">Table ### - Field ### - Property OptionCaption</note>
</trans-unit>
```
After you edit the translation and change the state (e.g., if you edit the translation in POEdit, the state of the trans-unit will be changed to "translated"), the "XLIFF Sync" note will be removed automatically when you run the command again.

Does this answer your question?

**Comment by pri-kise** [comment]
Ah thanks,

I don't know how i could have missed this additional line.

One issue was very tricky at first, since I had a souble space in the source string and the target string was perfect.
