### ISSUE TITLE
Wrong decoration

### ISSUE THREAD

**Issue by GregoryAA** [rvanbekkum/vsc-xliff-sync#39]
Hello Rob, 

if I change this setting xliffSync.missingTranslation to " " and restart vscode

I  will see wrong decoration in all files in my workspace. 

![image](https://user-images.githubusercontent.com/45356755/75427750-1e62b180-5958-11ea-887d-716f38a94b5d.png)

These are my settings:

    "xliffSync.findBySource": true,
    "xliffSync.missingTranslation": " ",
    "xliffSync.findBySourceAndDeveloperNote": true,
    "xliffSync.copyFromSourceForSameLanguage": true,
    "xliffSync.autoCheckNeedWorkTranslations": true,
    "xliffSync.autoCheckMissingTranslations": true

_Originally posted by @GregoryAA in https://github.com/rvanbekkum/vsc-xliff-sync/issues/31#issuecomment-591869727_

**Comment by rvanbekkum** [comment]
Hi @GregoryAA,
A fix for this issue will be shipped in v0.3.6 together with other optimizations for decorations.
