### ISSUE TITLE
Line ending changes should be ignored.

### ISSUE THREAD

**Issue by Lectem** [rvanbekkum/vsc-xliff-sync#41]
I am using the extension on windows where VSCode will generate CR+LF line endings.
However some tools such as angular (see https://github.com/angular/angular/issues/36057) will generate files with LF line endings.

This extension also generates CR+LF line endings when on windows.

This leads to changes being detected in for all translations units even if no changes were made on the base file.

**Comment by rvanbekkum** [comment]
Hi @Lectem,
Thank you for reporting your issue.

Do you mean that you would like to have (an option to have) line endings to be ignored in the code that checks whether the source text of a trans-unit has changed?
If I am misunderstanding or missing something, could you please further explain and/or give an example?
Thank you in advance for your response!

**Comment by Lectem** [comment]
> Do you mean that you would like to have (an option to have) line endings to be ignored in the code that checks whether the source text of a trans-unit has changed?

Yes exactly!

**Comment by rvanbekkum** [comment]
This change is shipped in version 0.3.7.
