### ISSUE TITLE
Copy from Source for Languages

### ISSUE THREAD

**Issue by rvanbekkum** [rvanbekkum/vsc-xliff-sync#44]
Check if it might be useful to add a new option `"xliffSync.copyFromSourceForLanguages" : []` that can be used to set the languages for which the translation can be copied from the source text.

**Comment by rvanbekkum** [comment]
This change is shipped in version 0.3.7.

**Comment by dd-ivanov** [comment]
@rvanbekkum is it possible to set a specific target state for copied from source translations, different from 'translated'?
