### ISSUE TITLE
Sync in combination with 'translation' apps

### ISSUE THREAD

**Issue by fvet** [rvanbekkum/vsc-xliff-sync#48]
We're looking into the option to move our Base App translation files into separate extensions for the translations that we ship (similar to how partners would have to add new languages to the app). Our repo structure could be as follows (xlf files are no longer part of the apps root folder) 

![image](https://user-images.githubusercontent.com/25268332/88518721-3adf4480-cff1-11ea-9516-22f36f559d5e.png)

Would it be possible for the XLIFF Sync commandlets to also act on xlf files that are part of other folders?

**Comment by rvanbekkum** [comment]
A new setting `xliffSync.syncCrossWorkspaceFolders` for this has been shipped in version 0.4.0.
With this setting you can change the behaviour of the extension: if set to `true`, then the extension will sync. from one base file in the workspace to all the other translation files in all of the workspace folders.
Thank you for reporting this issue. If you have any further feedback, please feel free to share!
