### ISSUE TITLE
Incorrect 'state' attribute "needs-translation" for XLIFF 2.0

### ISSUE THREAD

**Issue by antpyykk** [rvanbekkum/vsc-xliff-sync#50]
Hello Rob

---

There are in total [four states defined in XLIFF 2.0 specification](http://docs.oasis-open.org/xliff/xliff-core/v2.0/xliff-core-v2.0.html#state):

> - initial - indicates the segment is in its initial state
> - translated - indicates the segment has been translated
> - reviewed - indicates the segment has been reviewed
> - final - indicates the segment is finalized and ready to be used

The state attribute does not contain `needs-translation` nor `needs-adaption` like 1.2 spec.
Either `initial` state could be used or alternatively a custom [subState ](http://docs.oasis-open.org/xliff/xliff-core/v2.0/xliff-core-v2.0.html#substate)can be defined.

---

Just a minor inconvenience in an otherwise fantastic extension.

-Antti

**Comment by rvanbekkum** [comment]
Hi @antpyykk,
Thank you for filing this issue! I will look into it.

**Comment by rvanbekkum** [comment]
Hi @antpyykk,
I have mode changes to account for the states defined in the XLIFF 2.0 specification in the [`features/50-xlf2-states`](https://github.com/rvanbekkum/vsc-xliff-sync/tree/feature/50-xlf2-states) branch. You can find more information about the changes in the CHANGELOG in this branch:

> [**CHANGELOG.md**](https://github.com/rvanbekkum/vsc-xliff-sync/blob/feature/50-xlf2-states/CHANGELOG.md)
> * Better XLIFF 2.0 support:
>   * `state` attribute on `segment` nodes instead of target nodes.
>   * `state` and `subState` used:
>     * `needs-translation` -> `initial` with no sub-state
>     * `needs-adapatation` -> `translated` with sub-state configurable with setting `xliffSync.needsWorkTranslationSubstate`.
>     * `translated` -> `translated` with no sub-state.
>   * Let `xliffSync.fileType` = `xlf2` work with file-extension `xlf`.

Could you let me know if you can spot anything wrong or missing with these changes?

**Comment by antpyykk** [comment]
Excellent work @rvanbekkum . You sure work fast.

My only point would be to mention the default `subState` required for translation. Any reason for using `poedit:fuzzy`?
https://github.com/rvanbekkum/vsc-xliff-sync/blob/37f69c928b551223b3cbd4343b5d590de922d748/package.json#L154-L159

Other than that, this seems like it fixes the issue 👍

**Comment by rvanbekkum** [comment]
Thanks for your reply.

About the default `subState`:
I currently set it to the value that the application "[POEdit](https://poedit.net/)" adds to translations that you mark as 'needs work'.
What do you think might be a good default value for this setting? Do you think we should set it to something more general (e.g., "needsWork" or something similar) and let people customize it themselves in their user settings?

**Comment by antpyykk** [comment]
I really don't have an opinion on this. 

Quick search regarding `poedit:fuzzy` would indicate it marks the translation for automatic fuzzy translation - not neccessarily as "needs work".

[GitHub code search also didn't reveal many good candidates for naming the subState](https://github.com/search?l=&p=1&q=subState%3D%22+extension%3Axlf&ref=advsearch&type=Code)

Either introduce a custom namespace used exclusively by vsc-xliff-sync or keep the current poedit value. Nevertheless I think it will be overwritten by user settings.

**Comment by antpyykk** [comment]
@rvanbekkum if there's no further comments regarding this, I guess we could close the issue?

**Comment by rvanbekkum** [comment]
Hi @antpyykk,
The changes didn't make it into the `master` branch and the VS Marketplace just yet.
I would prefer to close it as soon as the changes make it into the `master` branch 😉.

**Comment by rvanbekkum** [comment]
Changes for this have been shipped in version 0.5.0.
Thanks again for reporting the issue!
