### ISSUE TITLE
Feature Request: Open Synced file in External Translation Tool

### ISSUE THREAD

**Issue by IceOnly** [rvanbekkum/vsc-xliff-sync#54]
An option to open the synced xliff file in an external translation tool would be niced, but only if the file needs something todo.
I use Poedit as a default tool for xliff files.
The workflow for me is currently build the AL package, sync the translation with ALT + X S and then open the file in poedit.

**Comment by rvanbekkum** [comment]
Hi @IceOnly,
Thank you for filing this issue. 

There is a setting `xliffSync.autoCheckMissingTranslations` and `xliffSync.autoCheckNeedWorkTranslations` that will trigger a check for missing translations or problems after syncing translations. If there are missing translations or problems in a file, then a message will be shown that will let you open the file in your default XLIFF editor. Is this what you are looking for?

If you already knew about these settings and they are not what you meant, then could you please explain what you'd like to be added/changed?

**Comment by IceOnly** [comment]
No, I did not know the feature, or rather, the result was not clear to me. Is it possible to confirm the notification without a mouse? I added a shortcut to focus the toast. But there a a lot of keys to hit to open the external tool.

**Comment by rvanbekkum** [comment]
Hi @IceOnly,
I think you cannot easily trigger the button on the toast(s) from the keyboard. I could see if I could add a setting to automatically open the files that have something to-do, but maybe you still want to give confirmation before that happens? What are your thoughts on this?

**Comment by rvanbekkum** [comment]
Hi @IceOnly,
Do you have further input for me on what you'd like to be changed?

**Comment by IceOnly** [comment]
Yes, this would be perfect. An option that automaticly run the default application if a translation is missing or needs work.

**Comment by fvet** [comment]
If this feature is added, please disable by default. I might be packaging my app and synching the translations, but I'm not responsible to update all the translation files. Some might be reviewed by the developer (in our case nl-BE, en-US), but others require external teams to provide translations (da-DK, fr-BE, de-DE, ..)

**Comment by rvanbekkum** [comment]
A new setting `xliffSync.openExternallyAfterEvent` has been shipped in 0.6.0 which you can use to have XLIFF Sync open files automatically after certain events take place!

**Comment by IceOnly** [comment]
Nice. Thank you!
