### ISSUE TITLE
Is it possible to disable or customize the auto note adding? 

### ISSUE THREAD

**Issue by htmnk** [rvanbekkum/vsc-xliff-sync#56]
As stated here: "The target node of the trans-units containing problems will be tagged with state="needs-adaptation". Additionally, a note will be added to the trans-unit to explain which problem was detected."

Is it possible to modify this so that the trans-units will be tagged but the notes are disabled completely?

**Comment by rvanbekkum** [comment]
Dear @htmnk,
Thank you for filing this issue.

Yes, seems like a setting that I could add 😉. I will check if I can add it in a next version!

**Comment by rvanbekkum** [comment]
A new setting `xliffSync.addNeedsWorkTranslationNote` has been shipped in 0.6.0 that you can use to enable or disable that notes are added that explain the detected problem!
