### ISSUE TITLE
Get an error when trying to syncronize to single file

### ISSUE THREAD

**Issue by spookymattress** [rvanbekkum/vsc-xliff-sync#58]
When I try to syncronize to a single file I get the error:

Command 'XLIFF: Synchronize to Single File' resulted in an error (command 'xliffSync.synchronizeFile' not found)

I have tried reinstalling the extension - it did not help.

Any ideas?

**Comment by rvanbekkum** [comment]
Hi @spookymattress,
Thank you for filing this issue.

No, not exactly yet. Do you have a project folder/workspace that you can share in which you keep experiencing this issue?
It sounds like the "XLIFF Sync" extension does not get activated for your workspace.
The extension currently has the following activationEvents declared in the `package.json` file:
```json
    "activationEvents": [
        "onCommand:xliffSync.synchronizeFile",
        "workspaceContains:**/*.xlf",
        "workspaceContains:**/*.xlf2",
        "onCommand:xliffSync.findNextMissingTarget"
    ],
```
It does include the `xliffSync.synchronizeFile` so it's weird that for some reason it still did not get activated for you.
(Sidenote: I also noticed that at least the command `xliffSync.createNewTargetFiles` should be included as well.)

**Comment by rvanbekkum** [comment]
Hi @spookymattress,
Do you have any more input of when you are running into this?

**Comment by rvanbekkum** [comment]
I am closing this issue. I did add activationEvents for all commands of the extension for the next release, so perhaps that was what you were running into. If you have any further input for me though, then please let me know.
