### ISSUE TITLE
VS Extension stopped synchronizing units

### ISSUE THREAD

**Issue by hendrik244** [rvanbekkum/vsc-xliff-sync#59]
Hi,

I used the tool a lot in the past, but since today it just don't synchronizes the translation files anymore.
What can I do to check, where this is coming from?
Is there a log I could check?
When I generate a new translation unit my new translations are in there, but when I try to sync my already created ones it just does nothing.

Best regards,
Hendrik

**Comment by rvanbekkum** [comment]
Hi @hendrik244,
I noticed you closed the issue yourself already. Was this intentional? Did you manage to resolve your issue yourself? If so, what turned out to be the issue for you?

**Comment by hendrik244** [comment]
hi @rvanbekkum,
the reason was that the xliff file was corrupt due a missing close of trans-unit tag.
Maybe a check if any of the xliff files to sync are all in right syntax would be a nice feature?
