### ISSUE TITLE
Seems to ignore the <alt-trans> Element

### ISSUE THREAD

**Issue by markusguenther** [rvanbekkum/vsc-xliff-sync#60]
Hello,

first at all thanks for that extension. I used it now the first time for syncing translations of our open source CMS.
It is a great helper.

But we are using xliff 1.2 which has specified the `alt-trans` element. When I now sync a translation and the english base language for instance does not have `alt-trans` the sync remove that.

I am not sure if it is a missing feature or a bug.
Would be nice to have a config for instance to ignore sub elements like alt-trans in the sync.

Thanks in advance 🙏

**Comment by rvanbekkum** [comment]
Hi @markusguenther,
Thanks for filing this issue. I will have a look at it! 😉

**Comment by markusguenther** [comment]
Thanks for taking care. If you need examples let me know :)

**Comment by rvanbekkum** [comment]
A change for this is ready and will be shipped in the next release. A new setting `xliffSync.preserveTargetChildNodes` has been added to account for this.

**Comment by rvanbekkum** [comment]
Shipped in v1.0.0.
