### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by waldo1001** [rvanbekkum/vsc-xliff-sync#65]
I'm constantly working in multiroot workspaces - it would be really helpful that error messages would indicate in which workspace the error was thrown:
![image](https://user-images.githubusercontent.com/12088142/101610902-21bbbb00-3a09-11eb-94f4-302666ecad16.png)

**Comment by rvanbekkum** [comment]
Hi @waldo1001,
Thank you for filing this issue.
I will include this in a next version. 🙂

**Comment by rvanbekkum** [comment]
Changes for this are shipped in v0.7.0!
