### ISSUE TITLE
Multiroot

### ISSUE THREAD

**Issue by waldo1001** [rvanbekkum/vsc-xliff-sync#66]
In a Multiroot workspace, it happens quite often that translations from one workspace is mixed/merged into translations from another workspace .. .

**Comment by waldo1001** [comment]
workspace per workspace is always ok

**Comment by rvanbekkum** [comment]
Hi @waldo1001,
So you mean from the generated (.g.xlf) file of one project folder into the .xlf files of another project folder in the workspace?
Do you know when this happens, or do you have a sample of how to reproduce that issue?

**Comment by waldo1001** [comment]
It happened a month ago for the first time.  I figured it was me doing something wrong so I didn't pay attention to it.

But now it happened for about 4 of the 67 workspaces.  It seems to be happening on different workspaces .. so a repro is going to be very difficult, I'm afraid :(.

I just re-ran the synch (after I already synched all translations), and look what happened here:
ETR-objects are from another workspace - also the xml if messed up:
![image](https://user-images.githubusercontent.com/12088142/101614923-cf30cd80-3a0d-11eb-87a6-bd1055236e77.png)

Same here:
![image](https://user-images.githubusercontent.com/12088142/101614965-de178000-3a0d-11eb-9e1a-1e18441d040b.png)

Here, it added thanslations from another app:
![image](https://user-images.githubusercontent.com/12088142/101615029-f4254080-3a0d-11eb-9004-69525f0dee4f.png)

You sometimes see it even in the header .. look how he took the PLF app translations, and put it in the EDI app:
![image](https://user-images.githubusercontent.com/12088142/101615203-28006600-3a0e-11eb-90da-c10cfef390c5.png)

here RESTWIN into FILE:
![image](https://user-images.githubusercontent.com/12088142/101615259-35b5eb80-3a0e-11eb-9094-6faf9bb2e468.png)

And finally DOCARCH into REST:
![image](https://user-images.githubusercontent.com/12088142/101615313-44040780-3a0e-11eb-9040-3a7389b8e446.png)

**Comment by waldo1001** [comment]
I think it's all the same issue .. getting data from another workspace and merge it into the wrong file .. .  I looked into your code, but I'm not that good with typescript to be able to debug - all seems good :-/.

I undid the above, and again, resynched - now without issues... .  So it's not really reproducable.

**Comment by waldo1001** [comment]
If I were to try to fix this issue - I would simply:
- not do it asyncronously (as it seems it's getting confused because of it)
- browse all workspaces
    - find app.json in workspace
    - run your sync for that workspace(using the app.json uri).

I don't care if it runs 65 times longer ;-).

**Comment by rvanbekkum** [comment]
Hmmm, thanks.  Will investigate, because this can be very disturbing. Indeed I think it might have something to do with asynchronous functions.
I will also give this one some higher priority over the other open issues, which are mostly enhancement requests.

**Comment by waldo1001** [comment]
Thanks - if I can help or test - let me know ;-)

**Comment by rvanbekkum** [comment]
I have made some changes which are likely to also resolve this issue. It's on the `develop` branch now and will be shipped in the next release.

**Comment by rvanbekkum** [comment]
Changes for this are shipped in v0.7.0!
