### ISSUE TITLE
Open VSX release

### ISSUE THREAD

**Issue by Matombo** [rvanbekkum/vsc-xliff-sync#85]
Hello,
and thanks for your simple yet very helpfull extension.
As I recently switched from VS Code to VS Codium:

Are you planing on also uploading the extension to open-vsx.org?

The VS Codium project does simply build and distributes installers for the VS Code github project.
Howevery because of licensing they are not allowed to put the microsoft marketplace url in the included default config. They opted for open-vsx.org instead.

While it's a trivial change to add the marketplace url on userside, having xliff-sync in the native repository would help discoverability for users that are not aware of the different extension sources.

**Comment by rvanbekkum** [comment]
Hi @Matombo,
Thank you for your message.

I did not have any plans for publishing the extension to open-vsx.org yet, but I think I will look into it. Thank you for the suggestion!

**Comment by rvanbekkum** [comment]
I think I will actually be withholding from this for now, as people that are using open-vsx will probably be proficient enough to add the VS Marketplace as an extension source.
