### ISSUE TITLE
Interested to demo your extension in a joined Areopa webinar?

### ISSUE THREAD

**Issue by lvanvugt** [rvanbekkum/vsc-xliff-sync#86]
Hi Rob,

Are you interested in demoing your VSCode extension in a Areopa webinar?
The idea is to have AL VSCode extension domed to the community.

If you're interested please let me know. Mail to: webinars@areopa.academy.

b rg
Luc van Vugt

**Comment by rvanbekkum** [comment]
Hi Luc,

Thank you for your message! I have sent you a mail, so I will also close the issue. 😉

Kind regards,
Rob
