### ISSUE TITLE
"Open externally" after synchronizing not opening the file.

### ISSUE THREAD

**Issue by dannoe** [rvanbekkum/vsc-xliff-sync#89]
After the latest vscode update (1.57.0) the "Open Externally" button on the "X missing translations(s)." dialog is not working correctly anymore. It will be shown and if I press it the following confirmation dialog will be shown:

![grafik](https://user-images.githubusercontent.com/7450586/121657848-12452980-caa1-11eb-9626-4e51c8ceed79.png)

But even after pressing "Yes" nothing happens.

What I tried so far:
- Reboot
- Reinstalling extension

**Comment by rvanbekkum** [comment]
Hi @dannoe,

Thank you for filing the issue, I see this is indeed an issue with the latest VSCode update. I did not find anyone who reported this to the VSCode team, but I suspect this must be an issue with other extensions as well, but I'll have to look into that a bit later.
If you find something in the meantime, please let me know. 😉

**Comment by dannoe** [comment]
Looks like the API you are using (``env.openExternal``) is not intended for opening files on the filesystem. (see [VS Code API](https://code.visualstudio.com/api/references/vscode-api#env.asExternalUri))
I found two extensions and they were both using ``open`` [open - npm](https://www.npmjs.com/package/open) for this functionality.

**Comment by rvanbekkum** [comment]
Reopening this until the fix is released with the next update.

**Comment by rvanbekkum** [comment]
Your patch has been applied in version 1.2.0! I will track https://github.com/microsoft/vscode/issues/126502 and see if we should act accordingly on that.
