### ISSUE TITLE
Synchronize Translation Units -  Syncs only ONE xlf FIle

### ISSUE THREAD

**Issue by aptMattKoe** [rvanbekkum/vsc-xliff-sync#96]
I have an workspace with the App and the Test App.
Only the "App" has different Translations like this:
![image](https://user-images.githubusercontent.com/57363453/131849014-3a178552-d9a6-4176-87bd-776fc7c8272e.png)

If I use "Synchronize Translation Units", the XLF Files that gets syncronized with "Single File" will get synced again:
![image](https://user-images.githubusercontent.com/57363453/131849556-dde247c4-3ae7-4153-b699-a501a991fbd7.png)

Any Ideas what I do wrong?

**Comment by rvanbekkum** [comment]
Hi @aptMattKoe,
Thank you for filing your issue!

Are you still running into the issue? Do you have a sample project that can reproduce the issue, so I can look into it? 🙂

**Comment by aptMattKoe** [comment]
I will try to build an example.
This project is nothing I could share :/

**Comment by aptMattKoe** [comment]
I tried it again today and now it works....I had no idea! Same project.
Sorry :/

**Comment by rvanbekkum** [comment]
No problem. Thanks for letting me know. 😊
