### ISSUE TITLE
Synchronize Translation Units function changes the note element closing tag

### ISSUE THREAD

**Issue by eclipses** [rvanbekkum/vsc-xliff-sync#97]
Hi, 

I've noted that "Synchronize Translation Units" function changes the note element closing tag

`<note from="Developer" annotates="general" priority="2"></note>`
becomes
`<note from="Developer" annotates="general" priority="2"/>`

If we look at the .g.xlf file generated automatically during compilation the closing tag is `</note>`

I verified also your corresponding function in PowerShell that does not change the closing tag. I suppose this is an issue of the VS Code extension.

**Comment by warlof** [comment]
I'm facing this issue myself, I hope the submitted PR would help :)
I keep the current working way and provide the ability to use open/closing tags instead of self-closing ones as an alternative.

**Comment by rvanbekkum** [comment]
I will release this with version 1.4.0.0 today.

**Comment by rvanbekkum** [comment]
A new setting `xliffSync.useSelfClosingTags` is now available in version 1.4.0.0. Thank you again @warlof!

**Comment by warlof** [comment]
Thank you for your amazing extension. That already saved us a lot of time since first Business Central extensions 👌

Now we will get even less dust on pull requests including translations files 😀
