### ISSUE TITLE
ParseFromDeveloperNote is case-sensitive

### ISSUE THREAD

**Issue by fvet** [rvanbekkum/vsc-xliff-sync#99]
While running some basic tests to parse translations from the DeveloperNote (in fact, from the 'comments' attached to a label, caption, ...) I found out this is case-sensitive.

![image](https://user-images.githubusercontent.com/25268332/151810956-d9c6175a-2212-42b6-9969-932c599c16a8.png)

Apparently the nl-**be** translation (_'Leverancier'_) is not extracted, since it does not match the target language nl-**BE**. Any chance in making the parse part case-insensitive, or do you see other reasons why this could not work?

Running following settings:

```
{
    "xliffSync.parseFromDeveloperNote": true,
    "xliffSync.parseFromDeveloperNoteOverwrite": true
}
```

**Comment by rvanbekkum** [comment]
I think in this case it might be better if the developer sticks to using `nl-BE` consistently as the RFC 4646 language for Dutch (Belgium). It is recommended to have the subtag capitalized, even though lowercase would be valid as well. But anyhow, I do think it would be better to stick to the convention prescribed by RFC. In that way there also won't be questions (or issues) raised "why is it written like that in one place, and like that in the other place?".

> As far as case sensitivity, they are case insensitive. From the RFC:
> 
> > The tags and their subtags, including private use and extensions, are to be treated as case insensitive: there exist conventions for the capitalization of some of the subtags, but these MUST NOT be taken to carry meaning.
> > 
> > For example:
> > 
> > [ISO639-1] recommends that language codes be written in lowercase('mn' Mongolian).
> > [ISO3166-1] recommends that country codes be capitalized ('MN' Mongolia).
> > [ISO15924] recommends that script codes use lowercase with the initial letter capitalized ('Cyrl' Cyrillic).
> > However, in the tags defined by this document, the uppercase US-ASCII letters in the range 'A' through 'Z' are considered equivalent and mapped directly to their US-ASCII lowercase equivalents in the range 'a' through 'z'.
> 
> So either lang="fa-ir" or lang="fa-IR" is correct but lang="fa-IR" is recommended.

**Comment by fvet** [comment]
Thanks for the feedback, should be no issue to explain people how to properly format the value, or encourage the use of your snippets instead ;)
